# Generated by Django 5.0.7 on 2024-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_rename_fname_contact_name_remove_contact_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
